name: Auto-increment Tags

on:
  push:
    branches:
      - main
      - githubactions

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get github context
      run: echo '${{ toJSON(github.event) }}' | jq

    - name: Echo tag message
      run: echo '${{ steps.meta.outputs.tags }}'

    - name: Echo label message
      run: echo '${{ steps.meta.outputs.labels }}'
      shell: bash

    - name: Get the latest tag
      id: get_latest_tag
      run: |
        latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.1.1")
        echo "latest_tag=$latest_tag" >> $GITHUB_ENV

    - name: Increment the tag
      id: increment_tag
      run: echo "next_tag=$(echo $latest_tag | awk -F. -v OFS=. '{$NF = $NF + 1; print}')" >> $GITHUB_ENV

    - name: Build Docker image
      run: docker build -t juhaszszabolcs90/askmate:${{ github.sha }} .

    - name: Set Docker image tag
      run: echo "tag=$next_tag" >> $GITHUB_ENV

    - name: Push Docker image
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Tag and Push Docker image with version
      run: |
        docker tag juhaszszabolcs90/askmate:${{ github.sha }} juhaszszabolcs90/askmate:$tag
        docker push juhaszszabolcs90/askmate:$tag

#check the idea of the context