name: askmate_szabi_version-app

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Build Docker image
      run: docker build -t juhaszszabolcs90/askmate:${{ github.sha }} .
      
    - name: Push Docker image
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
